[package]
name = "transparent_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
tap = "1.0.1"
tokio = { version = "1.16.1", features = ["full"] }
